/**
 * LOLBins Reference - Pre-rendering Build Script
 * 
 * Generates static HTML cards from js/data.js and injects them
 * into index.html so search engines can read the content immediately.
 * 
 * Idempotent: Safe to run multiple times without duplication.
 * 
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const INDEX_PATH = path.join(ROOT, 'index.html');
const DATA_PATH = path.join(ROOT, 'js', 'data.js');

// ─── 1. Load LOLBinsData from data.js ───────────────────────────────────────

function loadData() {
    let dataSource = fs.readFileSync(DATA_PATH, 'utf-8');
    // Replace 'const LOLBinsData' with 'var LOLBinsData' so it becomes a sandbox property
    dataSource = dataSource.replace(/^const\s+LOLBinsData\s*=/m, 'var LOLBinsData =');
    const vm = require('vm');
    const sandbox = {};
    vm.createContext(sandbox);
    vm.runInContext(dataSource, sandbox);
    
    if (!sandbox.LOLBinsData) {
        throw new Error('LOLBinsData not found in data.js');
    }
    return sandbox.LOLBinsData;
}

// ─── 2. Category label helper (mirrors app.js getCategoryLabel) ─────────────

function getCategoryLabel(category) {
    const labels = {
        'sudo': '🔓 Sudo', 'suid': '⚡ SUID', 'shell': '💀 Shell',
        'capabilities': '🎯 Caps', 'file-read': '📖 Read', 'file-write': '✏️ Write',
        'reverse-shell': '🔄 RevShell', 'bind-shell': '🔗 Bind',
        'file-upload': '📤 Upload', 'file-download': '📥 Download',
        'library-load': '📚 Library', 'limited-suid': '⚠️ Limited',
        'download': '📥 Download', 'execute': '⚡ Execute',
        'uac-bypass': '🛡️ UAC', 'awl-bypass': '🚫 AWL',
        'compile': '🔨 Compile', 'encode': '🔐 Encode',
        'recon': '🔍 Recon', 'ads': '📎 ADS', 'copy': '📋 Copy',
    };
    return labels[category] || category;
}

// ─── 3. Escape HTML (mirrors app.js escapeHtml) ────────────────────────────

function escapeHtml(text) {
    if (!text) return '';
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

// ─── 4. Generate card HTML (mirrors app.js createCardHTML) ──────────────────

function createCardHTML(item) {
    const categories = item.categories || [];
    const tagsHTML = categories
        .map(cat => `<span class="tag ${cat}">${getCategoryLabel(cat)}</span>`)
        .join('');
    const mitreTechnique = item.mitre?.technique || 'N/A';
    const description = escapeHtml(item.description || 'No description available');

    return `<div class="card" data-name="${escapeHtml(item.name)}">
            <div class="card-header">
                <h3 class="card-title">${escapeHtml(item.name)}</h3>
                <span class="card-os-badge">🪟</span>
            </div>
            <p class="card-description">${description}</p>
            <div class="card-tags">${tagsHTML}</div>
            <div class="card-mitre">
                <span class="mitre-label">MITRE:</span>
                <span class="mitre-id">${escapeHtml(mitreTechnique)}</span>
            </div>
        </div>`;
}

// ─── 5. Main build function ─────────────────────────────────────────────────

function build() {
    console.log('🚀 LOLBins Pre-rendering Build Started...\n');

    // Load data
    const data = loadData();
    const windowsBins = data.windows || [];
    const linuxBins = data.linux || [];

    console.log(`  📦 Loaded: ${windowsBins.length} Windows + ${linuxBins.length} Linux = ${windowsBins.length + linuxBins.length} total binaries`);

    // Generate Windows "All" cards (default view)
    const cardsHTML = windowsBins.map(item => createCardHTML(item)).join('\n            ');

    console.log(`  🔧 Generated ${windowsBins.length} pre-rendered card elements`);

    // Read index.html
    let html = fs.readFileSync(INDEX_PATH, 'utf-8');

    // ── Idempotent injection: Replace everything between cardsContainer tags ──
    // Match: <div class="cards-container" id="cardsContainer">...anything...</div>
    // followed by the no-results div
    const containerRegex = /(<div\s+class="cards-container"\s+id="cardsContainer">)([\s\S]*?)(\n\s*<\/div>\s*\n\s*<!-- No Results)/;
    
    if (!containerRegex.test(html)) {
        throw new Error('Could not find <div id="cardsContainer"> in index.html');
    }

    const preRenderedContent = `\n            <!-- PRE-RENDERED: ${windowsBins.length} Windows cards for SEO (generated by build.js) -->\n            ${cardsHTML}\n        `;
    
    html = html.replace(containerRegex, `$1${preRenderedContent}$3`);

    // ── Update counts ──
    html = html.replace(
        /(<span\s+class="tab-count"\s+id="windowsCount">)\d*(<\/span>)/,
        `$1${windowsBins.length}$2`
    );
    html = html.replace(
        /(<span\s+class="tab-count"\s+id="linuxCount">)\d*(<\/span>)/,
        `$1${linuxBins.length}$2`
    );

    // ── Update resultsCount ──
    html = html.replace(
        /(<span\s+id="resultsCount">)[^<]*(<\/span>)/,
        `$1Showing ${windowsBins.length} binaries$2`
    );

    // ── Add <noscript> if not already present ──
    if (!html.includes('<noscript>')) {
        const noscriptTag = `\n    <!-- No-JS Fallback -->\n    <noscript>\n        <style>.config-bar,.search-container,.filters-container,.view-toggle,.resources-btn{display:none!important}</style>\n        <div style="text-align:center;padding:2rem;color:#f0c040;font-size:1.1rem;">\n            ⚠️ JavaScript is required for search, filtering, and interactive features. The binary reference cards are visible below.\n        </div>\n    </noscript>`;
        
        html = html.replace(
            /(<main\s+class="main-content">)/,
            `$1${noscriptTag}`
        );
    }

    // ── Update dateModified in JSON-LD ──
    const today = new Date().toISOString().split('T')[0];
    html = html.replace(
        /"dateModified":\s*"[^"]*"/,
        `"dateModified": "${today}"`
    );

    // Write back
    fs.writeFileSync(INDEX_PATH, html, 'utf-8');

    // Stats
    const fileSizeKB = (Buffer.byteLength(html, 'utf-8') / 1024).toFixed(1);
    console.log(`  💾 Written to index.html (${fileSizeKB} KB)`);
    console.log(`  📊 Counts updated: Windows=${windowsBins.length}, Linux=${linuxBins.length}`);
    console.log(`  📅 dateModified updated to: ${today}`);
    console.log(`\n✨ Pre-rendering complete!\n`);
}

// Run
try {
    build();
} catch (err) {
    console.error('❌ Build failed:', err.message);
    process.exit(1);
}
